# For more info on HTTP files go to https://aka.ms/vs/httpfile
@server=https://localhost:7161
@token=Bearer dc78981390ab44f8a1bd254f6605ad6c

POST {{server}}/sessions/credentials
Content-Type: application/json
{
  "email":"test@hash.com",
  "password":"!12345679"
}
###

POST {{server}}/accounts/credentials
Content-Type: application/json
{
  "appId": "289926a3-8265-4f6e-9bf5-d896c7064711",
  "email": "test@hash.com",
  "password": "!12345678",
  "firstName": "prueba",
  "lastName": "prueba",
  "locale": "Uruguay",
  "timeZone": "-3",
  "profilePictureId": null
}
###

POST {{server}}/apps
Content-Type: application/json
Authorization: {{token}}
{
  "name":"test",
  "isDefault":false,
  "coverId":"688dd06c-41d0-4c3d-9374-4ff106c5eeca",
  "backgroundCoverId":"688dd06c-41d0-4c3d-9374-4ff106c5eeca"
}

###

GET {{server}}/apps?page=1&pageSize=10
Authorization:{{token}}

###

GET {{server}}/roles
Authorization:{{token}}

###
GET {{server}}/me
Authorization:{{token}}